#ifndef KEYMAP_HPP_
#define KEYMAP_HPP_

#include <usb/usb_device.h>
#include <usb/class/usb_hid.h>

struct Key {
	uint32_t scancode;
	uint32_t modifier;
};

const Key keymap[8][9] = {
	{
		{ HID_KEY_ESC, false },
		{ HID_KEY_1, false },
		{ HID_KEY_2, false },
		{ HID_KEY_3, false },
		{ HID_KEY_4, false },
		{ HID_KEY_5, false },
		{ HID_KEY_6, false },
		{ HID_KEY_7, false },
		{ HID_KEY_8, false },
	},
	{
		{ HID_KEY_9, false },
		{ HID_KEY_0, false },
		{ HID_KEY_MINUS, false },
		{ HID_KEY_EQUAL, false },
		{ HID_KEY_BACKSPACE, false },
		{ HID_KEY_HOME, false },
		{ HID_KEY_PAGEUP, false },
		{ HID_KEY_TAB, false },
		{ HID_KEY_Q, false },
	},
	{
		{ HID_KEY_W, false },
		{ HID_KEY_E, false },
		{ HID_KEY_R, false },
		{ HID_KEY_T, false },
		{ HID_KEY_Y, false },
		{ HID_KEY_U, false },
		{ HID_KEY_I, false },
		{ HID_KEY_O, false },
		{ HID_KEY_P, false },
	},
	{
		{ HID_KEY_LEFTBRACE, false },
		{ HID_KEY_RIGHTBRACE, false },
		{ HID_KEY_BACKSLASH, false },
		{ HID_KEY_END, false },
		{ HID_KEY_PAGEDOWN, false },
		{ HID_KEY_CAPSLOCK, false },
		{ HID_KEY_A, false },
		{ HID_KEY_S, false },
		{ HID_KEY_D, false },
	},
	{
		{ HID_KEY_F, false },
		{ HID_KEY_G, false },
		{ HID_KEY_H, false },
		{ HID_KEY_J, false },
		{ HID_KEY_K, false },
		{ HID_KEY_L, false },
		{ HID_KEY_SEMICOLON, false },
		{ HID_KEY_APOSTROPHE, false },
		{ HID_KEY_ENTER, false },
	},
	{
		{ HID_KBD_MODIFIER_LEFT_SHIFT, true },
		{ HID_KEY_Z, false },
		{ HID_KEY_X, false },
		{ HID_KEY_C, false },
		{ HID_KEY_V, false },
		{ HID_KEY_B, false },
		{ HID_KEY_N, false },
		{ HID_KEY_M, false },
		{ HID_KEY_COMMA, false },
	},
	{
		{ HID_KEY_DOT, false },
		{ HID_KEY_SLASH, false },
		{ HID_KBD_MODIFIER_RIGHT_SHIFT, true },
		{ HID_KEY_UP, false },
		{ HID_KBD_MODIFIER_LEFT_CTRL, true },
		{ HID_KBD_MODIFIER_LEFT_UI, true },
		{ HID_KBD_MODIFIER_LEFT_ALT, true },
		{ HID_KEY_SPACE, false },
		{ HID_KBD_MODIFIER_RIGHT_ALT, true },
	},
	{
		{ 0, false },
		{ HID_KBD_MODIFIER_RIGHT_CTRL, true },
		{ HID_KEY_LEFT, false },
		{ HID_KEY_DOWN, false },
		{ HID_KEY_RIGHT, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
	},
};

const Key keymap_fn[8][9] = {
	{
		{ HID_KEY_GRAVE, false },
		{ HID_KEY_F1, false },
		{ HID_KEY_F2, false },
		{ HID_KEY_F3, false },
		{ HID_KEY_F4, false },
		{ HID_KEY_F5, false },
		{ HID_KEY_F6, false },
		{ HID_KEY_F7, false },
		{ HID_KEY_F8, false },
	},
	{
		{ HID_KEY_F9, false },
		{ HID_KEY_F10, false },
		{ HID_KEY_F11, false },
		{ HID_KEY_F12, false },
		{ HID_KEY_DELETE, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
	},
	{
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
	},
	{
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
	},
	{
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ HID_KEY_ENTER, false },
	},
	{
		{ HID_KBD_MODIFIER_LEFT_SHIFT, true },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
	},
	{
		{ 0, false },
		{ 0, false },
		{ HID_KBD_MODIFIER_RIGHT_SHIFT, true },
		{ 0, false },
		{ HID_KBD_MODIFIER_LEFT_CTRL, true },
		{ HID_KBD_MODIFIER_LEFT_UI, true },
		{ HID_KBD_MODIFIER_LEFT_ALT, true },
		{ 0, false },
		{ HID_KBD_MODIFIER_RIGHT_ALT, true },
	},
	{
		{ 0, false },
		{ HID_KBD_MODIFIER_RIGHT_CTRL, true },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
		{ 0, false },
	},
};

#endif /* KEYMAP_HPP_ */
